apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  name: spring-sensors
spec:
  build:
    buildpacks: {}
    path: ../..
    nonSecretEnv: # non-secret vars for build time
      - name: BP_JVM_VERSION
        value: "17"
  ports:
  - name: main
    port: 8080
  replicas: 1




